# This is a basic workflow to help you get started with Actions

name: Build Loritta

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 16

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Runs a single command using the runners shell
    - name: Build with Gradle
      run: "./gradlew build -Dgithub.build.id=$GITHUB_RUN_ID -Dbuild.number=$GITHUB_RUN_NUMBER -Dgit.branch=$GITHUB_REF -Dcommit.hash=$GITHUB_SHA -Dcompiled.at=${{ steps.current-time.outputs.time }}"

    # Upload Artifacts to GitHub
    # Loritta
    - uses: actions/upload-artifact@v2
      name: "Upload Loritta (Discord)"
      with:
        name: Loritta (Discord)
        path: src.*.jar

